<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>Fleetwright.Shipgen.Cli</RootNamespace>
    <AssemblyName>shipgen</AssemblyName>
    <PublishAot>true</PublishAot>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Fleetwright.Shipgen\Fleetwright.Shipgen.csproj" />
  </ItemGroup>

</Project>
